
- hosts: all
  vars:
    generation_dir: "{{ playbook_dir }}/../generated"

  tasks:
  - name: Transfer artifacts
    block:
    - name: Backup previous artifacts on each node
      # NOTE As of Ansible 2.4, remote copy doesn't support recursive copy of directory.
      shell: |
        . ~/.profile
        
        if [ -d quorum ]; then
          mv quorum/ quorum-{{ lookup('pipe','date +%y%m%dT%H%M%S') }}/
        fi
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
    
    - name: Remove previous artifacts except backup
      file:
        path: "{{ ansible_env.HOME }}/quorum/"
        state: absent
      
    - name: Copy respective artifacts into the nodes
      copy:
        src: "{{ generation_dir }}/quorum/{{ item.name }}/"
        dest: "{{ ansible_env.HOME }}/quorum/{{ item.name }}/"
        backup: false
        mode: 0600
        directory_mode: 0740
      with_items: "{{ quorum.nodes }}"
      
    # TODO Make configurable
    - name: Create 'static-nodes.json' file
      copy:
        src: "{{ ansible_env.HOME }}/quorum/{{ item.name }}/data/permissioned-nodes.json"
        dest: "{{ ansible_env.HOME }}/quorum/{{ item.name }}/data/static-nodes.json"
        remote_src: true
        backup: false
        mode: 0600
      with_items: "{{ quorum.nodes }}"
  
    # NOTE Quorum geth 2.0.0 has a bug about the location of permissioned-nodes.json
    #      By the official wiki, the file is supposed to be on datadir 
    #      But actually the geth try to find the file on the directory where geth is called.
    - name: Copy 'permissioned-nodes.json' and 'static-nodes.json' file to startup directory
      copy:
        src: "{{ ansible_env.HOME }}/quorum/{{ item.0.name }}/data/{{ item.1 }}"
        dest: "{{ ansible_env.HOME }}/quorum/{{ item.1 }}"
        remote_src: true
        backup: false
        mode: 0600
      with_nested: 
        - "{{ quorum.nodes }}"
        - ['permissioned-nodes.json', 'static-nodes.json']
      
    - name: Copy common configuration files into all nodes
      copy:
        src: "{{ generation_dir }}/quorum/{{ item }}"
        dest: "{{ ansible_env.HOME }}/quorum/{{ item }}"
        backup: true
        mode: 0600
      with_items: ['genesis.json']

    - name: Create directories for log files
      file:
        path: "{{ ansible_env.HOME }}/quorum/{{ item.name }}/logs"
        state: directory
        mode: 0750
      with_items: "{{ quorum.nodes }}"

    - name: Create empty log files
      file:
        path: "{{ ansible_env.HOME }}/quorum/{{ item.0.name }}/logs/{{ item.1 }}"
        state: touch
        mode: 0640 
      with_nested: 
        - "{{ quorum.nodes }}"
        - ['geth.log', 'constellation.log']
    when: (not common.quorum.skips.transfer_artifacts) and (quorum|default({})).nodes|default([]) 
    become: false
    tags: ['transfer']

  - name: Init Ethereum node using genesis block
    command: geth --datadir "{{ item.name }}/data" init genesis.json
    args:
      chdir: "{{ ansible_env.HOME }}/quorum"
    with_items : "{{ quorum.nodes }}"
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['init']
