
- hosts: all
  tasks:

    # TODO Rename previously generated file before
    - name: Generate cryptogen configuration file
      template: 
        src: "{{ inventory_dir }}/templates/crypto-config.yaml.j2"
        dest: "{{ inventory_dir }}/generated/crypto-config.yaml"
        mode: "u=rw,g=r,o=r"
      run_once: true
      delegate_to: 127.0.0.1
      
      