---
- hosts: all
  tasks:
    - name: Check global variable
      debug:
        msg: 
          - "host.requirement.go.ver.min : {{ host.requirement.go.ver.min }}"
          - "host.requirement.go.ver.recommanded : {{ host.requirement.go.ver.recommanded }}"
          - "host.requirement.go.ppas: {{ host.requirement.go.ppas }}"
    
    - name: Verify that the OS is Ubuntu
      assert:
        that:
          - "ansible_distribution == 'Ubuntu'"
      msg: "Currently {{ ansible_distribution }} is not supported."
    - name: Verify that the major version of OS is 16
      assert:
        that:
          - "ansible_distribution_major_version == '16'"
      msg: "Currently {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."

    - name: Check whether Go is installed and configured properly or not
      shell: |
        . ~/.profile
        if [ `sudo dpkg -l | awk '{print $2}' | grep -E '^golang-(1\.8-)?go$' | wc -l` -lt 1 ]; then
          exit 101 # Go is not installed
        fi
        
        if [ ! $GOPATH ]; then
          echo "GOPATH = $GOPATH" 
          exit 102;  # 'GOPATH' environment variable 
        fi
        if [ ! `which go` ]; then exit 103; fi

        go_ver=$(go version | sed 's/.*go\([1-9]\.[1-9][0-9]*\).*/\1/')
        go_ver_major=$(echo ${go_ver} | sed 's/\([1-9]\)\.[1-9][0-9]*/\1/')
        go_ver_minor=$(echo ${go_ver} | sed 's/[1-9]\.\([1-9][0-9]*\)/\1/')
        if [ ${go_ver_major} -lt 1 ] || ([ ${go_ver_major} -eq 1 ] && [ ${go_ver_minor} -lt 8 ]); then
          exit 104 # Go verion is not proper
        fi
      args:
        executable: /bin/bash
      register: go_verification
      become: false
      ignore_errors: true
    - name: Fail if Go is not intalled
      fail: msg="Go is not installed."
      when: go_verification.rc == 101
    - name: Fail if 'GOPATH' enviroment varialble is not set or empty
      fail: msg="'GOPATH' enviroment varialble is not set or empty."
      when: go_verification.rc == 102
    - name: Fail if go executable is not on 'PATH'
      fail: msg="Go executable is not on 'PATH'"
      when: go_verification.rc == 103

      
    - name : Update APT cache
      apt: 
        update_cache: yes
        cache_valid_time: "{{ 3600 * 24 }}"
        
      
