--- # Global variables
# For more, refer followings 
#   - http://docs.ansible.com/ansible/latest/intro_inventory.html#splitting-out-host-and-group-specific-data
#   - http://docs.ansible.com/ansible/latest/intro_inventory.html#default-groups

host:
  requirement:
    go:
      ver:
        min: '1.8'
        recommanded:  '1.8'
      apt: 
        package: "golang-1.8-go"  # TODO Try "golang-{{ host.requirement.go.ver.recommanded }}-go"
        repos: ['ppa:gophers/archive', 'ppa:longsleep/golang-backports'] # TODO Check it is possible or not to specify the source file name for PPA
    nodejs:
      ver: # For all Node.js releases, refer 'https://nodejs.org/en/download/releases/'
        pattern: '6\.\(9|10|11|12|13|14\)\.[0-9]+'
        min: '6.9'
        max: '7.0'
      apt:
        package: "nodejs"
        keys: ['https://deb.nodesource.com/gpgkey/nodesource.gpg.key']
        repos: 
          - 
            url: "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
            filename: 'nodesource'
          - 
            url: "deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
            filename: 'nodesource'
    npm:
      ver:
        pattern: '3\.10\.10'
        recommanded: '3.10.10'
    docker:
      ver:
        min: '7.03'

fabric:
  ver: 'x86_64-1.1.0-preview'
  orgs:
    org0:
      name: org0
      type: orderer
      domain: org0
      ca:
        hostname: ca0
        common_name: ca0
    org1:
      name: org1
      type: peer
    org2:
      name: org2
      type: peer
    org3:
      name: org3
      type: peer


docker:
  images:
    # For all list of Hyperledger Fabric repositories, refer https://hub.docker.com/u/hyperledger/
    base: &docker_image_base
      # If you would like to use registry other than Docker Hub, uncomment the following line and ..
      # registry: ''
      tag: "{{ fabric.ver }}"
    zookeeper:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-zookeeper'
    kafka:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-kafka'
    orderer:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-orderer'
    peer:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-peer'
    couchdb:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-couchdb'
    tools:
      <<: *docker_image_base
      repository: 'hyperledger/fabric-tools'
    ca: # CA Server
      <<: *docker_image_base
      repository: 'hyperledger/fabric-ca'