--- # Global variables
# For more, refer followings 
#   - http://docs.ansible.com/ansible/latest/intro_inventory.html#splitting-out-host-and-group-specific-data
#   - http://docs.ansible.com/ansible/latest/intro_inventory.html#default-groups

host:
  requirement:
    go:
      ver:
        min: "1.8"
        recommanded: "1.9"
      ppas: ["ppa:longsleep/golang-backports"]
    nodejs:
      ver:
        pattern: '6\.\(9|10|11|12|13|14\)\.[0-9]+'
        min: "6.9"
        max: "7.0"
    npm:
      ver:
        pattern: '3\.10\.10'
        
    docker:
      ver:
        min: "17.03"
        
        