all:
  hosts:
  # https://docs.ansible.com/ansible/2.7/user_guide/intro_inventory.html#list-of-behavioral-inventory-parameters
    controller:  # control machine
      ansible_host: localhost
      ansible_connection: local