# https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/common-application-properties.html

debug: false
trace: false

logging.level:
  org.springframework.boot.autoconfigure: ERROR

server:
  address: '127.0.0.1'
  port: 8080

management.endpoints:
  web.exposure.include: '*'

spring.main:
  allow-bean-definition-overriding: false

spring.output:
  ansi.enabled: always  # https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-logging.html#boot-features-logging-color-coded-output

spring.security:
  user:
    name: boot
    password: boot
