foo:
  bar: "FOO.BAR"

spring:
  application:
    name: 'Scaffold project for Spring Boot 2.0 + Solidity development'
    
quorum:
  address: '192.168.56.101'
  port: 8545
  
quorum-fallback:
  address: '192.168.0.2'
  port: 8055