all:
  hosts:
  # https://docs.ansible.com/ansible/2.7/user_guide/intro_inventory.html#list-of-behavioral-inventory-parameters
    controller:  # control machine
      ansible_host: localhost
      ansible_connection: local
    m001:
      ansible_host: 
      ansible_user: 
      ansible_ssh_pass: !vault |
      ansible_become_pass: "{{ ansible_ssh_pass }}"
    m002:
      ansible_host: 
      ansible_user: 
      ansible_ssh_pass: !vault |
      ansible_become_pass: "{{ ansible_ssh_pass }}"
    m003:
      ansible_host: 
      ansible_user: 
      ansible_ssh_pass: !vault |
      ansible_become_pass: "{{ ansible_ssh_pass }}"