
# https://eslint.org/docs/latest/use/configure/
# https://eslint.org/docs/latest/use/configure/configuration-files
# https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

env:
  es2020: true  # version 11

parserOptions:
  ecmaVersion: latest

globals:
  artifacts: readonly

ignores:
  - './tsconfig.json'
  - 'node_modules'

