# This file follows the setup flows described at https://www.brianchristner.io/how-to-setup-docker-monitoring/

version: '2.1'

services:
  influxsrv:
    image: tutum/influxdb
    # For configuring InfluxDB image, refer https://hub.docker.com/r/tutum/influxdb/
    ports:
      - "8083:8083"
      - "8086:8086"
    expose: ["8090", "8099"]
    volumes:
      - /var/influxdb:/data
    environment:
      ADMIN_USER: root
      PRE_CREATE_DB: cadvisor

  cadvisor:
    image: google/cadvisor:latest
    # For more on cAdvisor and InfluxDB, refer https://github.com/google/cadvisor/blob/master/docs/storage/influxdb.md
    command: -storage_driver=influxdb -storage_driver_host=influxsrv:8086 -storage_driver_db=cadvisor -storage_driver_user=root -storage_driver_password=root -storage_driver_secure=false
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    links:
      - influxsrv:influxsrv
  grafana:
    image: grafana/grafana
    # For more on Grafana configuration, refer http://docs.grafana.org/installation/configuration/
    ports:
      - "3000:3000"
    links:
      - influxsrv:influxsrv
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_AUTH_GITHUB_ENABLED: 'false'
      GF_AUTH_GOOGLE_ENABLED: 'false'
      GF_AUTH_BASIC_ENABLED: 'true'
      GF_AUTH_LDAP_ENABLED: 'false'
      INFLUXDB_HOST: localhost
      INFLUXDB_PORT: 8086
      INFLUXDB_NAME: cadvisor
      INFLUXDB_USER: root
      INFLUXDB_PASS: root
