quorum: 
  nodes:
    # References
    #   - https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
    - name: node1
      host: "{{ inventory_hostname }}"
      type: permissioned # 'static' or 'permissioned'
      port: 30303 # TCP listening port
      rpcport:  8545 # default 8545
      raftport: 50400
      discport: 0
      accounts:
        prepared:
          count: 2
          password: user1234
      constellation: #constellation node
        # For reference, refer https://github.com/jpmorganchase/constellation/blob/master/sample.conf
        port : 9000
        socket : constellation.ipc
        verbosity: 3 # 0: Fatal, 1: Warn, 2: Info, 3: Debug
      


        