quorum: 
  nodes:
    # References
    #   - https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
    - name: node1
      host: "{{ inventory_hostname }}"  # Reduntant, but required in some cases such as control machine local only tasks 
      type: permissioned # 'static' or 'permissioned'
      port: 30333 # TCP listening port
      rpcaddr: '0.0.0.0'
      rpcport:  8575 # default 8545
      raftport: 50430
      discport: 0
      verbosity: 4 # 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default: 3)
      accounts:
        prepared:
          count: 2
          password: 
      constellation: #constellation node
        name: tm1
        bootnode: true
        # For reference, refer https://github.com/jpmorganchase/constellation/blob/master/sample.conf
        port : 9030
        socket : tm1.ipc
        verbosity: 3 # 0: Fatal, 1: Warn, 2: Info, 3: Debug
        # tls: off # optional, enum('strict', 'off'), overriding common.quorum.constellation.tls
      


        