quorum: 
  nodes:
    # References
    #   - https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options
    - name: node1
      host: "{{ inventory_hostname }}"  # Reduntant, but required in some cases such as control machine local only tasks 
      type: permissioned # 'static' or 'permissioned'
      port: 30303 # TCP listening port
      rpcaddr: '127.0.0.1'
      rpcport:  8545 # default 8545
      raftport: 50400
      discport: 0
      verbosity: 3 # 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default: 3)
      accounts:
        prepared:
          count: 2
          password: 
      constellation: #constellation node
        # For reference, refer https://github.com/jpmorganchase/constellation/blob/master/sample.conf
        port : 9000
        socket : tm.ipc
        verbosity: 3 # 0: Fatal, 1: Warn, 2: Info, 3: Debug
        # tls: off # optional, enum('strict', 'off'), overriding common.quorum.constellation.tls
      


        