quorum: 
  nodes:
    - name: node2
      host: "{{ inventory_hostname }}"
      type: permissioned # 'static' or 'permissioned'
      port: 30303 # TCP listening port
      rpcport:  8545
      raftport: 50400
      discport: 0
      verbosity: 4 # 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default: 3)
      accounts:
        prepared:
          count: 1
          password: user1234
      constellation: 
        # For reference, refer https://github.com/jpmorganchase/constellation/blob/master/sample.conf
        port : 9000
        socket : constellation.ipc
        verbosity: 3 # 0: Fatal, 1: Warn, 2: Info, 3: Debug
        # tls: off # optional, enum('strict', 'off'), overriding common.quorum.constellation.tls