quorum: 
  nodes:
    - name: node2
      host: "{{ inventory_hostname }}"
      type: permissioned # 'static' or 'permissioned'
      port: 30303 # TCP listening port
      rpcport:  8545
      raftport: 50400
      discport: 0
      accounts:
        prepared:
          count: 1
          password: user1234
      tx_manager: # transaction manager
        port : 9000
        socket_file : tm.ipc