quorum:
  nodes:
    - name: node3
      host: "{{ inventory_hostname }}"
      type: permissioned
      port: 30313
      rpcport:  8555
      raftport: 50410
      discport: 0
      accounts:
        prepared:
          count: 3
          password: user1234
      constellation: 
        # For reference, refer https://github.com/jpmorganchase/constellation/blob/master/sample.conf
        port : 9000
        socket : constellation.ipc
        verbosity: 3 # 0: Fatal, 1: Warn, 2: Info, 3: Debug