containers:
  zookeepers:
    - name: zk1
      id: 1 # myid file of ZooKeeper
      
      # For configuration parameters of ZooKeeper, refer 'https://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_configuration' 
      config:
        clientPort: 2191 #default: 2181
        tickTime: 2000
        initLimit: 10
        syncLimit: 2
        quorumPort: 2898 #default: 2888
        electionPort: 3898 #default : 3888
  kafkas:
    - name: kafka1
      address: "{{ ansible_host }}"
      port: 9092 # default: 9092
      config:
        'broker.id': 1
        'message.max.bytes': 6000000 # 6MB, shoud be larger than Orderer.AbsoluteMaxBytes
        'min.insync.replicas': 2 # 1 < min.insync.replicas < default.replication.factor
        'zookeeper.connection.timeout.ms': 10000 # 10 sec
        'default.replication.factor': 3
        'replica.fetch.max.bytes': 6000000 # Orderer.AbsoluteMaxBytes < replica.fetch.max.bytes <= message.max.bytes
        'metrics.recording.level': INFO
      jvm:
        heapOpts: '-Xmx1024m -Xms1024m'
        performanceOpts: '-server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true'
        gcLogOpts: ''
        jmxOpts: '-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'
        jmxPort: !!int 9999
  orderers:
    - name: orderer1
      org: org0
      address: "{{ ansible_host }}"
      port: 7050 # default: 7050
      config: # follow naming convention of Fabric. (e.g.: https://github.com/hyperledger/fabric/blob/v1.1.0-preview/sampleconfig/orderer.yaml)
        General:
          LogLevel: info # (critical | error | warning | notice | info | debug), http://hyperledger-fabric.readthedocs.io/en/release/logging-control.html
          Profile:
            Enabled: false # default: false
            Address: 0.0.0.0:6060
        Kafka:
          Retry:
            ShortInterval: 1s
            ShortTotal: 30s
          Verbose: false
