containers:
  zookeepers:
    - name: zk3
      host: "{{ inventory_hostname }}"
      id: 3 # myid file of ZooKeeper
      
      # For configuration parameters of ZooKeeper, refer 'https://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_configuration' 
      config:
        clientPort: 2191 #default: 2181
        tickTime: 2000
        initLimit: 10
        syncLimit: 2
        quorumPort: 2898 #default: 2888
        electionPort: 3898 #default : 3888    
  cas: # CA Servers
    - name: ca0
      host: "{{ inventory_hostname }}"
      port: 7054 # defalut: 7054
      config:
        debug: false
        tls:
          enabled: false

  # For more refer
  #   - https://github.com/yahoo/kafka-manager
  #   - https://github.com/montana-ua/kafka-manager-docker
  kafkaManagers:
    - name: 'kafka-manager'
      host: "{{ inventory_hostname }}"
      port: 9010 #default: 9000
    