all:
  hosts:
    controller:  # control machine
      ansible_host: localhost
      ansible_connection: local
    m001:
      ansible_host: 
      ansible_user: 
    m002:
      ansible_host: 
      ansible_user: 
    m003:
      ansible_host: 
      ansible_user: 