
# https://eslint.org/docs/latest/use/configure/
# https://eslint.org/docs/latest/use/configure/configuration-files
# https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
# https://typescript-eslint.io/getting-started/

root: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'

env:
  es2018: true  # version 9

globals:
  artifacts: readonly

# ignorePatterns:

