# For more, refer
#  - https://prometheus.io/docs/introduction/install/#using-docker
#  - https://www.digitalocean.com/community/tutorials/how-to-install-prometheus-using-docker-on-ubuntu-14-04

version: '2.1'

services:
  prometheus:
    image: prom/prometheus   # https://hub.docker.com/r/prom/prometheus/
    ports:
      - "${PROMETHEUS_GUI_PORT:-9090}:9090"
    volumes:
      - ~/docker/etc/prometheus:/etc/prometheus
      # - ~/docker/prometheus:/prometheus
    #command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000 #causes error on 'http://localhost:9090/consoles/node.html'
    command:
      - -config.file=/etc/prometheus/prometheus.yml
      - -storage.local.path=/prometheus
      #- -storage.local.memory-chunks=10000
      - -web.console.libraries=/usr/share/prometheus/console_libraries
      - -web.console.templates=/usr/share/prometheus/consoles
  grafana:
    image: grafana/grafana
    # For more on Grafana configuration, refer http://docs.grafana.org/installation/configuration/
    ports:
      - "${GRAFANA_GUI_PORT:-3000}:3000"
    volumes:
      # - ~/docker/etc/grafana:/etc/grafana
      - ~/docker/var/lib/grafana:/var/lib/grafana
      # - ~/docker/var/log/grafana:/var/log/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin!@34'
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_AUTH_GITHUB_ENABLED: 'false'
      GF_AUTH_GOOGLE_ENABLED: 'false'
      GF_AUTH_BASIC_ENABLED: 'true'
      GF_AUTH_LDAP_ENABLED: 'false'
