# For more on Prometheus configuration, refer
#
#   - https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus.yml
#   - https://prometheus.io/docs/operating/configuration/

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: '5s'
    # For more on 'static_configs', refer https://prometheus.io/docs/operating/configuration/#%3Cstatic_config%3E
    static_configs: #'target_groups' are renamed to 'static_configs'
      - targets: ['172.17.0.1:9100', '10.250.46.57:9100', '10.250.46.237:9100', '10.250.46.137:9100', '10.250.46.64:9100']

