common:
  host:
    layout:
      git_repo_base: "~/git/repo" # base directory for git repositories
    requirement:
      go:
        ver:
          min: '1.8'
          recommanded:  '1.8'
        apt: 
          package: "golang-1.8-go"  # TODO Try "golang-{{ host.requirement.go.ver.recommanded }}-go"
          repos: ['ppa:gophers/archive', 'ppa:longsleep/golang-backports'] # TODO Check it is possible or not to specify the source file name for PPA
      nodejs:
        ver: # For all Node.js releases, refer 'https://nodejs.org/en/download/releases/'
          pattern: '6\.\(9|10|11|12|13|14\)\.[0-9]+'
          min: '6.9'
          max: '7.0'
        apt:
          package: "nodejs"
          keys: ['https://deb.nodesource.com/gpgkey/nodesource.gpg.key']
          repos: 
            - url: "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
              filename: 'nodesource'
            - url: "deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
              filename: 'nodesource'
      npm:
        ver:
          pattern: '3\.10\.10'
          recommanded: '3.10.10'
  
  quorum:
    skips:
        generate_data: false
    version:
      node: '2.0.0' # without leading 'v' from the target tag of quorum git repository at https://github.com/jpmorganchase/quorum 
      constellation: '0.3.0'
    download: # download URLs
      # constellation: 'https://github.com/jpmorganchase/constellation/releases/download/v0.2.0/constellation-0.2.0-ubuntu1604.tar.xz'
      constellation: 'https://github.com/jpmorganchase/constellation/releases/download/v0.3.0/constellation-0.3.0-ubuntu1604.tar.xz'
    genesis:
      # https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/genesis.json
      # https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format#subformat-genesis
      # Don't miss the single quotation marks around values to be treated as strings not numbers
      nonce: '0x0'
      mixhash: '0x00000000000000000000000000000000000000647572616c65787365646c6578'
      difficulty: '0x0'
      coinbase: '0x0000000000000000000000000000000000000000'
      timestamp: '0x00'
      parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000'
      extraData: '0x0000000000000000000000000000000000000000000000000000000000000000'
      gasLimit: '0xE0000000'
    rpcapi: 'admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum'
    
      