common:
  host:
    layout:
      git_repo_base: "{{ ansible_env.HOME }}/git/repo" # base directory for git repositories
    requirement:
      go:
        ver:
          min: '1.8'
          recommanded:  '1.9'
        apt: 
          package: "golang-1.9-go"  # TODO(Done) Try "golang-{{ common.host.requirement.go.ver.recommanded }}-go" - error !
          repos: ['ppa:gophers/archive', 'ppa:longsleep/golang-backports'] # TODO Check it is possible or not to specify the source file name for PPA
      nodejs:
        ver: # For all Node.js releases, refer 'https://nodejs.org/en/download/releases/'
          pattern: '6\.\(9|10|11|12|13|14\)\.[0-9]+'
          min: '6.9'
          max: '7.0'
        apt:
          package: "nodejs"
          keys: ['https://deb.nodesource.com/gpgkey/nodesource.gpg.key']
          repos: 
            - url: "deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
              filename: 'nodesource'
            - url: "deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
              filename: 'nodesource'
      npm:
        ver:
          pattern: '3\.10\.10'
          recommanded: '3.10.10'
      python:
        pip:
          apt:
            package: 'python-pip'
        libraries:
          - name: pexpect
            ver: '4.3'
      prometheus:
        download: https://github.com/prometheus/prometheus/releases/download/v2.1.0/prometheus-2.1.0.linux-amd64.tar.gz
        dpkg: http://http.us.debian.org/debian/pool/main/p/prometheus/prometheus_2.1.0+ds-1+b2_amd64.deb
        dependencies:
          - name: adduser
          - name: daemon
          - name: debconf
          - name: libc6
          - name: libjs-eonasdan-bootstrap-datetimepicker
          - name: libjs-jquery
          - name: libjs-jquery-hotkeys
          - name: libjs-moment
          - name: libjs-mustache
          - name: libjs-rickshaw
          - name: libjs-bootstrap
      prometheus-node-exporter:
        # Refer https://github.com/prometheus/node_exporter
        apt:
          package: "prometheus-node-exporter"
        collectors:
          enabled: 'diskstats,filesystem,meminfo,netdev,stat,time'
        log:
          level: warn
        #auth:
        #  user:
        #  pass:
      grafana:
        version: '5.0.0'
        downlaod: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.0.0_amd64.deb
      solc:
        apt:
          repos: ['ppa:ethereum/ethereum']
  
  quorum:
    skips:
      generate_artifacts: false
      transfer_artifacts: false
    cleans:
      ledger: false
      datadir: false
    log:
      rollovers: false
    version: '2.0.1' # without leading 'v' from the target tag of quorum git repository at https://github.com/jpmorganchase/quorum 
    genesis:
      # https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/genesis.json
      # https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format#subformat-genesis
      # Don't miss the single quotation marks around values to be treated as strings not numbers
      nonce: '0x0'
      mixhash: '0x00000000000000000000000000000000000000647572616c65787365646c6578'
      difficulty: '0x0'
      coinbase: '0x0000000000000000000000000000000000000000'
      timestamp: '0x00'
      parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000'
      extraData: '0x0000000000000000000000000000000000000000000000000000000000000000'
      gasLimit: '0xE0000000'
    cache: 640 # Megabytes of memory allocated to internal caching (min 16MB / database forced) (default: 128)
    trie-cache-gens: 360 # Number of trie node generations to keep in memory (default: 120)
    rpcapi: 'admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum'
    raftblocktime: 50 # Amount of time between raft block creations in milliseconds (default: 50) 
    constellation:
      version: '0.3.2'
      download: 'https://github.com/jpmorganchase/constellation/releases/download/v0.3.2/constellation-0.3.2-ubuntu1604.tar.xz'
      tls: strict # 'strict', 'off'
      tlsservertrust: 'insecure-no-validation' # options: whitelist, tofu, ca, ca-or-tofu, insecure-no-validation
      tlsclienttrust: 'insecure-no-validation' # options: whitelist, tofu, ca, ca-or-tofu, insecure-no-validation
    posority:
      version: '1.2.0'
      download: https://github.com/jpmorganchase/quorum/releases/download/v1.2.0/porosity 
