
- hosts: all
  vars:
    generation_dir: "{{ playbook_dir }}/../generated"

  tasks:
  - name: Copy respective artifacts into the nodes
    copy:
      src: "{{ generation_dir }}/quorum/{{ item.name }}/"
      dest: "{{ ansible_env.HOME }}/quorum/{{ item.name }}/"
      backup: true
      mode: 0600
      directory_mode: 0740
    with_items: "{{ quorum.nodes }}"
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['quorum']

  - name: Copy common configuration files into all nodes
    copy:
      src: "{{ generation_dir }}/quorum/{{ item }}"
      dest: "{{ ansible_env.HOME }}/quorum/{{ item }}"
      backup: true
      mode: 0600
    with_items: ['genesis.json', 'permissioned-nodes.json']
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['quorum']
    
  
  - name: Init Quorum node using genesis block
    command: geth --datadir "{{ item.name }}/data" init genesis.json
    args:
      chdir: "{{ ansible_env.HOME }}/quorum"
    with_items : "{{ quorum.nodes }}"
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['quorum']
