
- hosts: all
  tasks:


  - name: Clone or update Quorum source repository from GitHub
    git: 
      repo: 'https://github.com/jpmorganchase/quorum.git'
      dest: "{{ common.host.layout.git_repo_base }}/quorum"
      clone: true
      update: true
      version: "{{ common.quorum.version.node }}"
    when: (quorum|default({})).nodes|default([])
    become: false
    register: update_quorum_src_result
    changed_when: update_quorum_src_result.after != update_quorum_src_result.before
    tags: ['quorum-ndoe']
    
  - name: Build Quorum
    make:
     chdir: "{{ common.host.layout.git_repo_base }}/quorum"
     target: all
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['quorum-ndoe']
    
  - name: Copy Quorum binaries to '/usr/local/bin'
    copy:
      src:  "{{ common.host.layout.git_repo_base }}/quorum/build/bin/{{ item }}"
      dest: /usr/local/bin
      owner: root
      group : root
      mode: 0755
    with_items: ['geth', 'bootnode']
    when: (quorum|default({})).nodes|default([])
    become: true
    tags: ['quorum-ndoe']
    
  - name: Install packages required for Constellation node
    apt:
      name: "{{ item }}" 
    with_items: ['libdb-dev', 'libleveldb-dev', 'libsodium-dev', 'zlib1g-dev', 'libtinfo-dev']
    when: (quorum|default({})).nodes|default([])
    become: false
    tags: ['constellation']
    
  - name: Check whether the constellation is already installed or not
    command :  constellation-node --version
    when: (quorum|default({})).nodes|default([])
    become: true
    register: check_constellation_result
    changed_when: false
    tags: ['constellation']

  - name: Downlaod Constellation binary archive
    get_url:
      url: "{{ common.quorum.download.constellation }}" 
      dest: "~/Downloads"
      mode: 0644
    when: (quorum|default({})).nodes|default([]) and check_constellation_result.failed
    when: false
    become: false
    register: download_constellation_result
    tags: ['constellation']
      
  - name: Unzip Constellation binary archive
    vars: 
      filename: "{{ common.quorum.download.constellation|regex_replace('^.*/', '') }}"
    unarchive:
      src: "~/Downloads/{{ filename }}"
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
    when: (quorum|default({})).nodes|default([]) and download_constellation_result.changed
    become: true
    tags: ['constellation']
