- hosts: localhost
  vars:
      generation_dir: "{{ playbook_dir }}/../generated"
  tasks:
  

       
    - name: Generate key files for each transaction manager
      expect:
        command: constellation-node --generatekeys=tm
        responses:
           'Lock key pair.*' : ''
        chdir: "{{ generation_dir }}/quorum/data/{{ item.name }}-tm"
      with_items: "{{ hostvars.values()|selectattr('quorum', 'defined')|map(attribute='quorum')|selectattr('nodes', 'defined')|map(attribute='nodes')|sum(start=[])|list }}"
      become: false
    