# https://eth-brownie.readthedocs.io/en/latest/config.html


networks:
  default: development
  development:
    # local Ganache or Ganache-CLI is expected
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      port: 8545
      
      
console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true

# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
