# For more,
#   - https://docs.docker.com/compose/wordpress/
#   - https://hub.docker.com/_/wordpress/
#   - https://hub.docker.com/_/mysql/
version: '2.1'
services:
  db:
    image: mysql:5
    volumes:
      - ~/docker/etc/mysql:/etc/mysql
      - ~/docker/var/lib/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: workdpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:4
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
